'use client';
import Link from 'next/link';
import {useEffect,useState} from 'react';
import {AppShell} from '@/components/app-shell';
import {getSupabaseBrowserClient} from '@/lib/supabase-browser';
import {CalendarDays,Users,QrCode,Clock,UserCheck} from 'lucide-react';
type A={id:string;title:string;starts_at:string;ends_at:string;capacity:number;reservations?:{id:string}[]};
export default function Page(){const[aulas,setAulas]=useState(0);const[alunos,setAlunos]=useState(0);const[presencas,setPresencas]=useState(0);const[today,setToday]=useState<A|null>(null);useEffect(()=>{void(async()=>{const sb=getSupabaseBrowserClient();if(!sb)return;const{data:{user}}=await sb.auth.getUser();if(!user)return;const now=new Date(),start=new Date(now);start.setHours(0,0,0,0);const end=new Date(now);end.setHours(23,59,59,999);const[{count:c1},{count:c2},{data:classes},{data:todayRows}]=await Promise.all([sb.from('classes').select('*',{count:'exact',head:true}).eq('professor_id',user.id),sb.from('students').select('*',{count:'exact',head:true}).eq('responsible_professor_id',user.id),sb.from('classes').select('id').eq('professor_id',user.id),sb.from('classes').select('id,title,starts_at,ends_at,capacity,reservations(id)').eq('professor_id',user.id).gte('starts_at',start.toISOString()).lte('starts_at',end.toISOString()).neq('status','cancelled').order('starts_at')]);setAulas(c1||0);setAlunos(c2||0);setToday((todayRows?.[0] as A)||null);const ids=(classes||[]).map(x=>x.id);if(ids.length){const{count}=await sb.from('attendance').select('*',{count:'exact',head:true}).in('class_id',ids);setPresencas(count||0)}})()},[]);return <AppShell>
  <section className="welcome-hero professor-welcome"><div><span className="eyebrow">PAINEL DO PROFESSOR</span><h1>Seu tatame, sem complicação.</h1><p>Abra o app e encontre primeiro o que você precisa para dar aula.</p></div><div className="quick-actions professor-actions"><Link href="/aulas" className="quick-action"><CalendarDays size={20}/><span>Minhas aulas</span></Link><Link href="/check-in" className="quick-action"><QrCode size={20}/><span>Abrir QR</span></Link><Link href="/alunos" className="quick-action"><Users size={20}/><span>Meus alunos</span></Link></div></section>
  {today?<section className="card next-class-card"><div className="next-class-top"><div><span className="pill">AULA DE HOJE</span><h2>{today.title}</h2><div className="next-class-meta"><span><Clock size={16}/>{new Date(today.starts_at).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}</span><span><Users size={16}/>{today.reservations?.length||0}/{today.capacity} inscritos</span></div></div><div className="toolbar"><Link href="/aulas" className="btn btn-secondary">Ver alunos</Link><Link href={`/check-in?class=${today.id}`} className="btn btn-primary"><QrCode size={16}/> Mostrar QR</Link></div></div></section>:<div className="empty-state">Nenhuma aula sua programada para hoje. <Link href="/aulas">Ver agenda</Link></div>}
  <div className="grid grid-3 compact-stats" style={{marginTop:18}}><div className="card stat"><span className="muted">Aulas cadastradas</span><strong>{aulas}</strong></div><div className="card stat"><span className="muted">Alunos vinculados</span><strong>{alunos}</strong></div><div className="card stat"><span className="muted">Presenças registradas</span><strong>{presencas}</strong><small><UserCheck size={13}/> Histórico acumulado</small></div></div>
</AppShell>}
