'use client';
import {useEffect,useMemo,useState} from 'react';
import {AppShell} from '@/components/app-shell';
import {Award,RefreshCw,TrendingUp,AlertTriangle,Clock3,CalendarCheck,Medal,ChevronDown} from 'lucide-react';

type Belt={id:string;name:string;sort_order:number;minimum_months:number};
type Grad={id:string;graduation_date:string;degrees:number;notes?:string;from?:{name?:string}|null;to?:{name?:string}|null;professor?:{name?:string}|null};
type Evo={score:number;status:string;attendance30:number;attendance60:number;attendance90:number;totalAttendance:number;streakWeeks:number;trainingMonths:number;monthsInBelt:number;eventCount:number;competitionCount:number;graduationCount:number;daysAbsent:number|null;risk:string;components:Record<string,number>};
type Student={id:string;degrees:number;profiles?:{name?:string;avatar_url?:string}|null;belts?:{id?:string;name?:string;minimum_months?:number;sort_order?:number}|null;evolution:Evo;graduations:Grad[]};

export default function Page(){const[data,setData]=useState<{role:string;students:Student[];belts:Belt[]}>({role:'aluno',students:[],belts:[]});const[loading,setLoading]=useState(true);const[msg,setMsg]=useState('');const[selected,setSelected]=useState<Student|null>(null);const[form,setForm]=useState({to_belt_id:'',degrees:0,graduation_date:new Date().toISOString().slice(0,10),notes:''});
  async function load(){setLoading(true);const r=await fetch('/api/evolution',{cache:'no-store'});const j=await r.json();if(r.ok)setData(j);else setMsg(j.error||'Falha ao carregar evolução.');setLoading(false)}
  useEffect(()=>{void load()},[]);
  const summary=useMemo(()=>{const s=data.students;return {avg:s.length?Math.round(s.reduce((a,x)=>a+x.evolution.score,0)/s.length):0,risk:s.filter(x=>['alto','atencao'].includes(x.evolution.risk)).length,excellent:s.filter(x=>x.evolution.score>=80).length,active30:s.filter(x=>x.evolution.attendance30>0).length}},[data.students]);
  async function recalc(id:string){setMsg('Atualizando IEA...');const r=await fetch('/api/evolution',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'recalculate',student_id:id})});const j=await r.json();setMsg(r.ok?'IEA atualizado com sucesso.':j.error||'Falha ao atualizar IEA.');if(r.ok)await load()}
  async function graduate(e:React.FormEvent){e.preventDefault();if(!selected)return;setMsg('Registrando graduação...');const r=await fetch('/api/evolution',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'graduate',student_id:selected.id,...form})});const j=await r.json();setMsg(r.ok?'Graduação registrada com sucesso.':j.error||'Falha ao registrar graduação.');if(r.ok){setSelected(null);await load()}}
  return <AppShell><section className="hero"><div className="split"><div><h1>Evolução dos atletas</h1><div className="muted">Frequência, sequência, tempo de treino, histórico de graduação e IEA em um único lugar.</div></div><button className="btn btn-secondary" onClick={load}><RefreshCw size={15}/> Atualizar</button></div></section>
    {msg&&<div className={msg.includes('sucesso')?'notice success':'notice error'} style={{marginBottom:14}}>{msg}</div>}
    {data.role!=='aluno'&&<div className="grid grid-4 compact-stats"><div className="card stat"><span className="muted">IEA médio</span><strong>{summary.avg}</strong><small>Equipe acompanhada</small></div><div className="card stat"><span className="muted">Treinaram em 30 dias</span><strong>{summary.active30}</strong><small>Alunos ativos no tatame</small></div><div className="card stat"><span className="muted">Excelente evolução</span><strong>{summary.excellent}</strong><small>IEA 80 ou mais</small></div><div className="card stat attention"><span className="muted">Precisam de atenção</span><strong>{summary.risk}</strong><small>Queda ou ausência recente</small></div></div>}
    {loading?<div className="empty-state" style={{marginTop:18}}>Calculando evolução...</div>:!data.students.length?<div className="empty-state" style={{marginTop:18}}>Ainda não há histórico suficiente para exibir evolução.</div>:<div className="evolution-list">{data.students.map(s=><article className="card evolution-card" key={s.id}><div className="evolution-head"><div className="student-cell">{s.profiles?.avatar_url?<img src={s.profiles.avatar_url} className="student-avatar" alt=""/>:<div className="student-avatar mini"><Award size={16}/></div>}<div><h2>{s.profiles?.name||'Aluno'}</h2><div className="muted">{s.belts?.name||'Sem faixa'} • {s.degrees||0} grau(s)</div></div></div><div className={`iea-score ${s.evolution.score>=80?'good':s.evolution.score<40?'risk':''}`}><strong>{s.evolution.score}</strong><span>IEA</span></div></div>
      <div className="evolution-grid"><div><CalendarCheck size={16}/><span>30 dias</span><strong>{s.evolution.attendance30} treinos</strong></div><div><TrendingUp size={16}/><span>Sequência</span><strong>{s.evolution.streakWeeks} semana(s)</strong></div><div><Clock3 size={16}/><span>Tempo total</span><strong>{s.evolution.trainingMonths} meses</strong></div><div><Medal size={16}/><span>Faixa atual</span><strong>{s.evolution.monthsInBelt} meses</strong></div></div>
      <div className="progress-line"><div><span>Status</span><strong>{s.evolution.status}</strong></div><div className="progress-track"><span style={{width:`${s.evolution.score}%`}}/></div></div>
      <div className="evolution-actions">{s.evolution.risk!=='normal'&&<span className="risk-note"><AlertTriangle size={15}/>{s.evolution.daysAbsent===null?'Sem presença registrada':`${s.evolution.daysAbsent} dias sem treinar`}</span>}<div className="toolbar">{data.role!=='aluno'&&<button className="btn btn-secondary" onClick={()=>recalc(s.id)}>Salvar IEA</button>}{data.role!=='aluno'&&<button className="btn btn-primary" onClick={()=>{setSelected(s);const current=Number(s.belts?.sort_order||0);const next=data.belts.find(b=>b.sort_order===current+1)||data.belts.find(b=>b.id===s.belts?.id);setForm({...form,to_belt_id:next?.id||''})}}><Award size={15}/> Registrar graduação</button>}</div></div>
      {!!s.graduations?.length&&<details className="history-details"><summary><ChevronDown size={15}/> Histórico de graduações ({s.graduations.length})</summary><div className="history-list">{s.graduations.map(g=><div key={g.id}><strong>{g.to?.name||'-'} • {g.degrees||0} grau(s)</strong><span>{new Date(g.graduation_date+'T12:00:00').toLocaleDateString('pt-BR')} {g.professor?.name?`• ${g.professor.name}`:''}</span>{g.notes&&<small>{g.notes}</small>}</div>)}</div></details>}
    </article>)}</div>}
    {selected&&<div className="modal-backdrop"><form className="card modal-card" onSubmit={graduate}><h2>Registrar graduação</h2><p className="muted">{selected.profiles?.name} • IEA atual {selected.evolution.score}. O IEA é apenas apoio; a decisão é sempre do professor.</p><label className="label">Nova faixa</label><select className="input" value={form.to_belt_id} onChange={e=>setForm({...form,to_belt_id:e.target.value})} required><option value="">Selecione</option>{data.belts.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select><label className="label">Graus</label><input className="input" type="number" min="0" max="6" value={form.degrees} onChange={e=>setForm({...form,degrees:Number(e.target.value)})}/><label className="label">Data</label><input className="input" type="date" value={form.graduation_date} onChange={e=>setForm({...form,graduation_date:e.target.value})} required/><label className="label">Observações</label><textarea className="input" rows={3} value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/><div className="toolbar"><button className="btn btn-primary">Confirmar graduação</button><button type="button" className="btn btn-secondary" onClick={()=>setSelected(null)}>Cancelar</button></div></form></div>}
  </AppShell>}
