import {NextResponse} from 'next/server';
import {z} from 'zod';
import {getSupabaseAdmin,getSupabaseServerClient} from '@/lib/supabase-server';
import {buildEvolution} from '@/lib/evolution';

async function gate(){const sb=await getSupabaseServerClient(),admin=getSupabaseAdmin();if(!sb||!admin)return {error:NextResponse.json({error:'Supabase não configurado'},{status:503})};const {data:{user}}=await sb.auth.getUser();if(!user)return {error:NextResponse.json({error:'Não autenticado'},{status:401})};const {data:profile}=await admin.from('profiles').select('role,active').eq('id',user.id).single();if(!profile||profile.active===false)return {error:NextResponse.json({error:'Acesso inativo'},{status:403})};return {admin,user,role:profile.role as 'admin'|'professor'|'aluno'};}

export async function GET(){const g=await gate();if('error'in g)return g.error;let q=g.admin.from('students').select('id,start_date,last_graduation_date,degrees,status,responsible_professor_id,profiles!students_id_fkey(name,avatar_url),belts(id,name,minimum_months,sort_order)').eq('status','ativo').order('start_date');if(g.role==='aluno')q=q.eq('id',g.user.id);if(g.role==='professor')q=q.eq('responsible_professor_id',g.user.id);const {data:students,error}=await q;if(error)return NextResponse.json({error:error.message},{status:500});const ids=(students||[]).map(s=>s.id);if(!ids.length)return NextResponse.json({role:g.role,students:[],belts:[]});const since=new Date();since.setFullYear(since.getFullYear()-3);const [att,parts,grads,belts]=await Promise.all([g.admin.from('attendance').select('student_id,checked_in_at').in('student_id',ids).gte('checked_in_at',since.toISOString()),g.admin.from('event_participants').select('student_id,events(event_type)').in('student_id',ids),g.admin.from('graduations').select('id,student_id,graduation_date,degrees,notes,iea_score,from:belts!graduations_from_belt_id_fkey(name),to:belts!graduations_to_belt_id_fkey(name),professor:profiles!graduations_professor_id_fkey(name)').in('student_id',ids).order('graduation_date',{ascending:false}),g.admin.from('belts').select('id,name,sort_order,minimum_months').order('sort_order')]);const now=new Date();const result=(students||[]).map((s:any)=>({...s,evolution:buildEvolution(s,(att.data||[]) as any,(parts.data||[]) as any,(grads.data||[]) as any,now),graduations:(grads.data||[]).filter((x:any)=>x.student_id===s.id)}));return NextResponse.json({role:g.role,students:result,belts:belts.data||[]});}

const actionSchema=z.discriminatedUnion('action',[z.object({action:z.literal('recalculate'),student_id:z.string().uuid()}),z.object({action:z.literal('graduate'),student_id:z.string().uuid(),to_belt_id:z.string().uuid(),degrees:z.coerce.number().int().min(0).max(6).default(0),graduation_date:z.string().min(10),notes:z.string().optional().nullable()})]);
export async function POST(req:Request){const g=await gate();if('error'in g)return g.error;if(g.role==='aluno')return NextResponse.json({error:'Sem permissão'},{status:403});const p=actionSchema.safeParse(await req.json());if(!p.success)return NextResponse.json({error:'Dados inválidos.'},{status:400});const d=p.data;const {data:student}=await g.admin.from('students').select('id,start_date,last_graduation_date,degrees,belt_id,responsible_professor_id,belts(id,name,minimum_months,sort_order)').eq('id',d.student_id).single();if(!student)return NextResponse.json({error:'Aluno não encontrado.'},{status:404});if(g.role==='professor'&&student.responsible_professor_id!==g.user.id)return NextResponse.json({error:'Este aluno não está vinculado a você.'},{status:403});const [att,parts,grads]=await Promise.all([g.admin.from('attendance').select('student_id,checked_in_at').eq('student_id',d.student_id),g.admin.from('event_participants').select('student_id,events(event_type)').eq('student_id',d.student_id),g.admin.from('graduations').select('student_id,graduation_date').eq('student_id',d.student_id)]);const evo=buildEvolution(student as any,(att.data||[]) as any,(parts.data||[]) as any,(grads.data||[]) as any);
  if(d.action==='recalculate'){const {error}=await g.admin.from('iea_scores').insert({student_id:d.student_id,score:evo.score,frequency:evo.components.frequency,streak:evo.components.streak,training_time:evo.components.trainingTime,events:evo.components.events,competitions:evo.components.competitions,graduation:evo.components.graduation,attendance:evo.components.attendance});return error?NextResponse.json({error:error.message},{status:500}):NextResponse.json({ok:true,evolution:evo});}
  const {error}=await g.admin.from('graduations').insert({student_id:d.student_id,from_belt_id:(student as any).belt_id||null,to_belt_id:d.to_belt_id,degrees:d.degrees,graduation_date:d.graduation_date,professor_id:g.user.id,iea_score:evo.score,notes:d.notes||null});if(error)return NextResponse.json({error:error.message},{status:500});return NextResponse.json({ok:true});
}
