import { NextResponse } from 'next/server';
import { z } from 'zod';
import { getSupabaseAdmin, getSupabaseServerClient } from '@/lib/supabase-server';

const schema=z.object({
 name:z.string().min(2),email:z.string().email(),phone:z.string().optional(),cpf:z.string().optional(),
 birth_date:z.string().optional(),sex:z.string().optional(),weight:z.number().optional(),height:z.number().optional(),
 category_id:z.string().uuid().optional(),responsible_professor_id:z.string().uuid().optional(),start_date:z.string().optional(),
 belt_id:z.string().uuid().optional(),degrees:z.number().int().min(0).max(4).default(0),last_graduation_date:z.string().optional(),
 notes:z.string().optional(),emergency_contact:z.string().optional(),injuries:z.string().optional(),plan_id:z.string().uuid().optional(),
 status:z.enum(['ativo','inativo','bloqueado']).default('ativo')
});
async function gate(){const sb=await getSupabaseServerClient();const admin=getSupabaseAdmin();if(!sb||!admin)return {error:NextResponse.json({error:'Supabase não configurado'},{status:503})};const {data:{user}}=await sb.auth.getUser();if(!user)return {error:NextResponse.json({error:'Não autenticado'},{status:401})};const {data:p}=await admin.from('profiles').select('role').eq('id',user.id).single();if(!p||!['admin','professor'].includes(p.role))return {error:NextResponse.json({error:'Sem permissão'},{status:403})};return {admin};}
export async function POST(req:Request){const g=await gate();if('error'in g)return g.error;const parsed=schema.safeParse(await req.json());if(!parsed.success)return NextResponse.json({error:'Dados inválidos',details:parsed.error.flatten()},{status:400});const d=parsed.data;const {data:inv,error}=await g.admin.auth.admin.inviteUserByEmail(d.email,{data:{name:d.name},redirectTo:`${process.env.NEXT_PUBLIC_APP_URL||'http://localhost:3000'}/update-password`});if(error||!inv.user)return NextResponse.json({error:error?.message||'Falha ao convidar aluno'},{status:400});await g.admin.from('profiles').update({name:d.name,email:d.email,phone:d.phone||null,role:'aluno'}).eq('id',inv.user.id);const {error:studentError}=await g.admin.from('students').insert({id:inv.user.id,cpf:d.cpf||null,birth_date:d.birth_date||null,sex:d.sex||null,weight:d.weight||null,height:d.height||null,category_id:d.category_id||null,responsible_professor_id:d.responsible_professor_id||null,start_date:d.start_date||new Date().toISOString().slice(0,10),belt_id:d.belt_id||null,degrees:d.degrees,last_graduation_date:d.last_graduation_date||null,notes:d.notes||null,emergency_contact:d.emergency_contact||null,injuries:d.injuries||null,plan_id:d.plan_id||null,status:d.status});if(studentError){await g.admin.auth.admin.deleteUser(inv.user.id);return NextResponse.json({error:studentError.message},{status:500});}return NextResponse.json({id:inv.user.id,name:d.name,email:d.email},{status:201})}
export async function GET(){const g=await gate();if('error'in g)return g.error;const {data,error}=await g.admin.from('students').select('id,cpf,birth_date,sex,weight,height,degrees,start_date,last_graduation_date,training_time_months,notes,emergency_contact,injuries,status,profiles!students_id_fkey(name,email,phone),belts(name),plans(name),categories(name)').order('start_date',{ascending:false});if(error)return NextResponse.json({error:error.message},{status:500});return NextResponse.json(data)}
