'use client';
import Link from 'next/link';
import {useEffect,useState} from 'react';
import {AppShell} from '@/components/app-shell';
import {getSupabaseBrowserClient} from '@/lib/supabase-browser';
import {CalendarDays,ScanLine,Award,UserCircle,Clock,Users,CheckCircle2} from 'lucide-react';
type NextClass={id:string;title:string;starts_at:string;ends_at:string;capacity:number;reservations?:{id:string}[];my?:{status?:string}|null};
export default function Page(){const[treinos,setTreinos]=useState(0);const[mes,setMes]=useState(0);const[iea,setIea]=useState(0);const[faixa,setFaixa]=useState('-');const[graus,setGraus]=useState(0);const[next,setNext]=useState<NextClass|null>(null);useEffect(()=>{void(async()=>{const sb=getSupabaseBrowserClient();if(!sb)return;const{data:{user}}=await sb.auth.getUser();if(!user)return;const startMonth=new Date();startMonth.setDate(1);startMonth.setHours(0,0,0,0);const[{count},{count:monthCount},{data:scores},{data:student},{data:classes}]=await Promise.all([sb.from('attendance').select('*',{count:'exact',head:true}).eq('student_id',user.id),sb.from('attendance').select('*',{count:'exact',head:true}).eq('student_id',user.id).gte('checked_in_at',startMonth.toISOString()),sb.from('iea_scores').select('score').eq('student_id',user.id).order('calculated_at',{ascending:false}).limit(1),sb.from('students').select('degrees,belts(name)').eq('id',user.id).maybeSingle(),sb.from('classes').select('id,title,starts_at,ends_at,capacity,reservations(id)').gte('starts_at',new Date().toISOString()).eq('status','open').order('starts_at').limit(1)]);setTreinos(count||0);setMes(monthCount||0);setIea(Number(scores?.[0]?.score||0));const b=student?.belts as unknown as {name?:string}|null;setFaixa(b?.name||'-');setGraus(Number(student?.degrees||0));setNext((classes?.[0] as NextClass)||null)})()},[]);return <AppShell>
  <section className="student-welcome"><div><span className="eyebrow">MEU TREINO</span><h1>Sua próxima aula vem primeiro.</h1><p>Reserve, faça o check-in e acompanhe sua evolução sem procurar em vários menus.</p></div></section>
  {next?<section className="card student-next-class"><div className="split"><span className="pill">PRÓXIMA AULA</span><span className="muted">{new Date(next.starts_at).toLocaleDateString('pt-BR',{weekday:'long',day:'2-digit',month:'short'})}</span></div><h2>{next.title}</h2><div className="next-class-meta"><span><Clock size={16}/>{new Date(next.starts_at).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}</span><span><Users size={16}/>{next.reservations?.length||0}/{next.capacity} vagas ocupadas</span></div><div className="toolbar"><Link href="/aulas" className="btn btn-primary"><CalendarDays size={16}/> Reservar aula</Link><Link href="/check-in/scan" className="btn btn-secondary"><ScanLine size={16}/> Fazer check-in</Link></div></section>:<div className="empty-state">Ainda não há uma próxima aula aberta. A agenda aparecerá aqui assim que o professor publicar.</div>}
  <div className="grid grid-4 student-stats" style={{marginTop:18}}><div className="card stat"><span className="muted">Treinos no mês</span><strong>{mes}</strong></div><div className="card stat"><span className="muted">Treinos realizados</span><strong>{treinos}</strong></div><div className="card stat"><span className="muted">Graduação</span><strong className="belt-stat">{faixa}</strong><small>{graus} grau(s)</small></div><div className="card stat"><span className="muted">IEA atual</span><strong>{iea.toFixed(1)}</strong><small>{iea?'Evolução calculada':'Aguardando histórico'}</small></div></div>
  <section className="student-shortcuts"><Link href="/aulas" className="student-shortcut"><CalendarDays/><span>Agenda</span><small>Reservar ou cancelar</small></Link><Link href="/check-in/scan" className="student-shortcut"><ScanLine/><span>Check-in</span><small>Ler QR da aula</small></Link><Link href="/graduacoes" className="student-shortcut"><Award/><span>Evolução</span><small>Faixa e progresso</small></Link><Link href="/perfil" className="student-shortcut"><UserCircle/><span>Perfil</span><small>Seus dados</small></Link></section>
  {!treinos&&<div className="onboarding-tip"><CheckCircle2 size={18}/><div><strong>Seu histórico começa no primeiro check-in.</strong><span>Depois disso, frequência, sequência, IEA e conquistas serão alimentados automaticamente.</span></div></div>}
</AppShell>}
