'use client';
import {useEffect,useMemo,useState} from 'react';import {Plus,RefreshCw,Pencil} from 'lucide-react';
type Field={name:string;label:string;type?:'text'|'number'|'select'|'time';options?:{value:string;label:string}[];required?:boolean};
export function SimpleCrud({title,subtitle,endpoint,fields,columns,defaults={}}:{title:string;subtitle:string;endpoint:string;fields:Field[];columns:{key:string;label:string;render?:(row:any)=>React.ReactNode}[];defaults?:Record<string,any>}){
 const[rows,setRows]=useState<any[]>([]);const[open,setOpen]=useState(false);const[form,setForm]=useState<Record<string,any>>(defaults);const[msg,setMsg]=useState('');const[editing,setEditing]=useState<string|null>(null);
 async function load(){const r=await fetch(endpoint,{cache:'no-store'});const j=await r.json();if(r.ok)setRows(j);else setMsg(j.error||'Falha ao carregar')}
 useEffect(()=>{void load()},[]);
 const titleButton=editing?'Salvar alterações':'Salvar cadastro';
 function startEdit(row:any){const next={...defaults};for(const f of fields)next[f.name]=row[f.name]??defaults[f.name]??'';setForm(next);setEditing(row.id);setOpen(true);setMsg('')}
 async function save(e:React.FormEvent){e.preventDefault();setMsg('Salvando...');const r=await fetch(endpoint,{method:editing?'PATCH':'POST',headers:{'content-type':'application/json'},body:JSON.stringify({...form,...(editing?{id:editing}:{})})});const j=await r.json();if(!r.ok){setMsg(j.error||'Falha ao salvar');return}setMsg('Cadastro salvo com sucesso.');setOpen(false);setEditing(null);setForm(defaults);await load()}
 const body=useMemo(()=>rows,[rows]);
 return <><section className="hero"><div className="split"><div><h1>{title}</h1><div className="muted">{subtitle}</div></div><button className="btn btn-primary" onClick={()=>{setOpen(v=>!v);setEditing(null);setForm(defaults)}}><Plus size={16}/> Novo cadastro</button></div></section>
 {msg&&<div className={msg.includes('sucesso')?'notice success':'notice error'} style={{marginBottom:14}}>{msg}</div>}
 {open&&<form className="card admin-form" onSubmit={save}><div className="grid grid-3">{fields.map(f=><div key={f.name}><label className="label">{f.label}</label>{f.type==='select'?<select className="input" value={String(form[f.name]??'')} onChange={e=>setForm({...form,[f.name]:f.name==='active'?e.target.value==='true':e.target.value})} required={f.required}><option value="">Selecione...</option>{f.options?.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select>:<input className="input" type={f.type==='number'?'number':f.type==='time'?'time':'text'} value={form[f.name]??''} onChange={e=>setForm({...form,[f.name]:f.type==='number'?Number(e.target.value):e.target.value})} required={f.required}/>}</div>)}</div><div className="toolbar" style={{marginTop:16}}><button className="btn btn-primary">{titleButton}</button><button type="button" className="btn btn-secondary" onClick={()=>{setOpen(false);setEditing(null)}}>Cancelar</button></div></form>}
 <div className="card" style={{padding:18}}><div className="split" style={{marginBottom:12}}><strong>{rows.length} registro(s)</strong><button className="btn btn-secondary" onClick={load}><RefreshCw size={14}/> Atualizar</button></div>{!body.length?<div className="empty-state">Nenhum cadastro ainda.</div>:<div className="table-wrap"><table className="table"><thead><tr>{columns.map(c=><th key={c.key}>{c.label}</th>)}<th>Ações</th></tr></thead><tbody>{body.map(row=><tr key={row.id}>{columns.map(c=><td key={c.key}>{c.render?c.render(row):String(row[c.key]??'-')}</td>)}<td><button className="icon-btn" onClick={()=>startEdit(row)} title="Editar"><Pencil size={15}/></button></td></tr>)}</tbody></table></div>}</div></>
}
